name: Deploy to Amazon EKS

on:
  push:
    branches: [ "dev" ]
  pull_request:

env:
  AWS_REGION: us-east-2                
permissions:
  contents: read
  pull-requests: write
defaults:
      run:
        shell: bash
        working-directory: starter/terraform
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true 

    - name: Terraform Plan
      run: terraform plan -input=false

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
    #   run: terraform apply -auto-approve -input=false

